# Generated by Django 3.0.6 on 2020-06-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Calories', models.IntegerField(default=0)),
                ('Time', models.TimeField()),
                ('UserID', models.IntegerField(default=0)),
            ],
        ),
    ]
