# Generated by Django 3.0.6 on 2020-06-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DietManApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditems',
            name='UserID',
        ),
        migrations.AddField(
            model_name='fooditems',
            name='Username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
