# Generated by Django 3.0.6 on 2020-06-05 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DietManApp', '0003_auto_20200606_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='Time',
            field=models.TimeField(default=datetime.time(2, 50, 45, 944653)),
        ),
    ]
