# Generated by Django 3.0.6 on 2020-06-06 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DietManApp', '0004_auto_20200606_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='Time',
            field=models.TimeField(default=datetime.time(6, 55, 26, 611136)),
        ),
    ]
