# Generated by Django 3.0.6 on 2020-06-07 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DietManApp', '0005_auto_20200606_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='Time',
            field=models.TimeField(default=datetime.time(15, 32, 14, 844722)),
        ),
    ]
