# Generated by Django 3.0.6 on 2020-06-08 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DietManApp', '0006_auto_20200607_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='Type',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='Time',
            field=models.TimeField(default=datetime.time(8, 11, 32, 518467)),
        ),
    ]
